// <auto-generated />
using Core.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Core.Migrations
{
    [DbContext(typeof(TimeTrackerDbContext))]
    [Migration("20220307025030_CreateEventHistorySummaryView")]
    partial class CreateEventHistorySummaryView
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
