version: 0.2

env:
    variables:
        ROOT_FOLDER: TimeTracker
        DOTNET_CORE_RUNTIME: 3.1
        ENTRY: ./${ROOT_FOLDER}/WebApi/WebApi

phases:
    install:
        runtime-versions:
            dotnet: ${DOTNET_CORE_RUNTIME}

    pre_build:
        commands:
            - echo Restore started on `date`
            - dotnet restore ${ENTRY}.csproj

    build:
        commands:
            - echo Build started on `date`
            - dotnet build -c Debug ${ENTRY}.csproj

    post_build:
        commands:
            - echo Publish started on `date`
            - dotnet publish -c Debug -r linux-x64 -o ./build_output ${ENTRY}.csproj --self-contained false
            - cp ./${ROOT_FOLDER}/Procfile ./build_output

artifacts:
    files:
        - '**/*'
    base-directory: ./build_output
    discard-paths: no
